# vars file for task1-role


required_packages:
  - nginx
  - git
  - python3
  - python3-pip
  - python3-venv
  - curl
  - wget
  - htop
  - tree
  - unzip

python_packages:
  - flask

docker_packages:
  - docker.io
  - docker-compose
  - python3-docker

docker_compose_path: "/opt/{{ app_name }}/docker-compose.yml"
docker_nginx_directory: "/opt/{{ app_name }}/nginx"

