# vars file for task1-role


required_packages:
  - git
  - python3
  - python3-pip
  - python3-venv
  - curl
  - wget
  - htop
  - tree
  - unzip

nginx_package:
  - nginx

python_packages:
  - flask

docker_packages:
  - docker.io
  - docker-compose
  - python3-docker

docker_compose_path: "{{ app_directory }}/docker-compose.yml"
docker_nginx_directory: "{{ app_directory }}/nginx"

