- name: Install Nginx for traditional deployment
  apt:
    name: nginx
    state: present
  tags: 
    - traditional
    - nginx

- name: Configure Nginx
  template:
    src: "nginx-app.conf.j2"
    dest: "/etc/nginx/sites-available/{{ app_name }}"
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart nginx
  tags: nginx

- name: Enable Nginx site
  file:
    src: "/etc/nginx/sites-available/{{ app_name }}"
    dest: "/etc/nginx/sites-enabled/{{ app_name }}"
    state: link
  notify:
    - restart nginx
  tags: nginx
